apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapi
  namespace: crud-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: final_assignment-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: db_address
              value: crud-service
            - name: db_port
              value: "5432"
            - name: db_username
              value: postgres
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: dbpassword
                  key: POSTGRES_PASSWORD
            - name: db_name
              value: postgres

