apiVersion: v1
kind: Namespace
metadata:
  name: crud-app
---
apiVersion: v1
kind: Secret
metadata:
  name: rotc-secret
  namespace: crud-app
type: Opaque
data:
  db-password: QXAwMHJQYSQkdzByZCE=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotc-db-deployment
  namespace: crud-app
  labels:
    app: rotc-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotc-db
  template:
    metadata:
      labels:
        app: rotc-db
    spec:
      containers:
      - name: rotc-db
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rotc-secret
              key: db-password
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: crud-app
spec:
  type: ClusterIP
  selector:
    app: rotc-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotc-backend-deployment
  namespace: crud-app
  labels:
    app: rotc-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotc-backend
  template:
    metadata:
      labels:
        app: rotc-backend
    spec:
      containers:
      - name: rotc-backend
        image: final_assignment-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: db_address
          value: db-service
        - name: db_username
          value: postgres
        - name: db_name
          value: postgres
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: rotc-secret
              key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: crud-app
spec:
  type: ClusterIP
  selector:
    app: rotc-backend
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /rotc/postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
