apiVersion: v1
kind: Secret
metadata:
  name: rotc-secret
type: Opaque
data:
  db-password: QXAwMHJQYSQkdzByZCE=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotc-db-deployment
  labels:
    app: rotc-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotc-db
  template:
    metadata:
      labels:
        app: rotc-db
    spec:
      containers:
      - name: rotc-db
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rotc-secret
              key: db-password

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: rotc-db
  ports:
    - port: 5432
      targetPort: 5432