apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: crud-application
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /postgres  
  persistentVolumeReclaimPolicy: Retain

